# Generated by Django 2.1 on 2019-11-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20191108_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandShadow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handshadows', related_query_name='handshadow', to='recruitment.Recruit')),
                ('sith', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.Sith')),
            ],
        ),
    ]
