# Generated by Django 2.1 on 2019-12-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_auto_20191109_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
