# Generated by Django 2.1 on 2019-12-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_auto_20191203_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='uid',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
