# Generated by Django 2.1 on 2020-01-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_auto_20191205_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='handshadow',
            name='isWelcomeMailSent',
            field=models.BooleanField(default=False),
        ),
    ]
